#!/usr/bin/env node
/**
 * Screen import — turns a `.scr` ZX Spectrum screen dump into a TypeScript module
 * the bundler can inline, so a full-screen picture costs no network request.
 *
 * STANDARD (screen import):
 *   - Source = a 6912-byte `.scr` written by zxart (`engine/zx-art/art/<project>/screens/`), which
 *     is the *authoring* format. A PNG may only ever be an input reference for the
 *     generator or an output preview — never the asset the game ships.
 *   - `.scr` is 6144 bytes of bitmap followed by 768 attribute bytes. Its three-bit
 *     INK and PAPER fields cannot name a colour outside the 16, cannot hold more
 *     than one ink and one paper per cell, and carry one BRIGHT bit for the whole
 *     cell — so an off-palette or clash-breaking screen is not expressible. That is
 *     the whole reason this pipeline exists and a PNG one does not.
 *   - Output = `src/assets/<name>.ts` exporting the bytes as base64. The game calls
 *     `parseSCR()` from zx-kit on them; the de-interleave lives there, not here, so
 *     there is exactly one implementation of it.
 *   - Inlining is the point: an `<img>` that fails to load leaves a scene with
 *     nothing to draw and no way forward. A module cannot half-arrive.
 *
 * Unlike `sprite-import.mjs` there is no segmentation, downsampling or palette
 * snapping. The source is already pixel-exact and hardware-valid by construction;
 * this only changes the container.
 *
 * Usage: node scripts/screen-import.mjs [in.scr] [--write]
 *   (no --write = dry run: prints the summary only)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const SCR_BYTES = 6912
const ARGS = process.argv.slice(2)
const WRITE = ARGS.includes('--write')
const INPUT = ARGS.find((a) => !a.startsWith('--')) ?? 'src/assets/minefield-loading.scr'
const OUT_DIR = 'src/assets'

const bytes = readFileSync(INPUT)
if (bytes.length !== SCR_BYTES) {
  console.error(`screen-import: ${INPUT} is ${bytes.length} bytes, expected ${SCR_BYTES}.`)
  process.exit(1)
}

const name = path.basename(INPUT, '.scr')
const constant = `${name.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}_SCR`
const base64 = bytes.toString('base64')

// Report what the attributes actually contain — the numbers a reviewer would
// otherwise have to take on trust, and the ones that decide where UI may go.
const colours = new Set()
let flashCells = 0
let brightCells = 0
for (let i = 0; i < 768; i++) {
  const attr = bytes[SCR_BYTES - 768 + i]
  const bright = (attr & 0x40) !== 0
  if (attr & 0x80) flashCells++
  if (bright) brightCells++
  colours.add(`${bright ? 'B' : ''}${attr & 7}`)
  colours.add(`${bright ? 'B' : ''}${(attr >> 3) & 7}`)
}

const wrapped = base64.match(/.{1,96}/g).join("' +\n  '")
const file = `// GENERATED by scripts/screen-import.mjs — do not edit.
// Source: ${path.basename(INPUT)} (${SCR_BYTES} bytes: 6144 bitmap + 768 attributes)
//
// A native ZX Spectrum screen dump, inlined as base64 so it is part of the bundle
// rather than a request that can fail. Decode it with parseSCR() from zx-kit.
//
// Regenerate: node scripts/screen-import.mjs ${INPUT} --write

const BASE64 =
  '${wrapped}'

/** Raw ${SCR_BYTES}-byte screen dump. Pass to \`parseSCR()\`. */
export const ${constant}: Uint8Array = Uint8Array.from(atob(BASE64), (c) => c.charCodeAt(0))
`

const outPath = path.join(OUT_DIR, `${name}.ts`)
console.log(`${INPUT} -> ${outPath}`)
console.log(`  bytes        : ${SCR_BYTES}  (base64 ${base64.length} chars)`)
console.log(`  palette used : ${colours.size} of 16 entries`)
console.log(`  BRIGHT cells : ${brightCells} of 768`)
console.log(`  FLASH cells  : ${flashCells} of 768`)

if (!WRITE) {
  console.log('\ndry run — pass --write to emit the module')
} else {
  writeFileSync(outPath, file)
  console.log(`\nwrote ${outPath} (${file.length} bytes)`)
}
