// GENERATED by scripts/screen-import.mjs — do not edit.
// Source: minefield-loading.scr (6912 bytes: 6144 bitmap + 768 attributes)
//
// A native ZX Spectrum screen dump, inlined as base64 so it is part of the bundle
// rather than a request that can fail. Decode it with parseSCR() from zx-kit.
//
// Regenerate: node scripts/screen-import.mjs src/assets/minefield-loading.scr --write

const BASE64 =
  '/////////////////////////wLAAAIAAAAFkgfM/77/////////////////////////CA+DAAAAAd/A////////////////' +
  '//////////////8I/////wQA////////////////////////////////////////AAD/////////////////////////////' +
  '//////////8AAP////////8AAQD//wD//////////////////////xj///////////////8AAAD//wD/////////////////' +
  'AAD/////AAD/////////////////AAD///////////8v0P///wABIP////////////////////////8aApAAAAAABfAAAAAQ' +
  '/////////////////////////wgB/AAAAAB4AP//////////////////////////////CP////8KAP//////////////////' +
  '/////////////////////wAA////////////////////////////////////////AYD/////////AAAA//8A////////////' +
  '//////////8o////////////////ABAA//8A/////////////////wAA/////wAA/////////////////wAA////////////' +
  'EED///8AAAD/////////////////////////ehLUAAAAAAb0AAAAgP////////////////////////8AABv/f8AAAAD/////' +
  '/////////////////////////wD/////HwD///////////////////////////////////////8AAP//////////////////' +
  '/////////////////////wAA/////////wYgMP//AP//////////////////////fP///////////////4ABAP//AP//////' +
  '//////////8AAP////8AAP////////////////8AAP///////////wcA////AAAA//////////////////////////oAAPB/' +
  'gAACDAAABAD/////////////////////////CAAAAAA+AAAA//////////////////////////////8A/////z+A////////' +
  '////////////////////////////////AYD///////////////////////////////////////8AAP////////8GYDD//wD/' +
  '//////////////////////7///////////////8AAAD//wD/////////////////AgD/////AAD/////////////////EID/' +
  '//////////8AAP///wAAAP////////////////////////9+AAAAABgAAIAAAgAA/////////////////////////wgAAAAA' +
  'AAAAAP//////////////////////////////AP////9/wP///////////////////////////////////////wKA////////' +
  '////////////////////////////////AAD/////////AAAw//8A////////////////////////////////////////AAAA' +
  '//8A/////////////////wMA/////wAA/////////////////wAA////////////AAD///8EAID/////////////////////' +
  '////GgAAHAADAAAAAfAAAP////////////////////////8IAAAAAAAAAAD//////////////////////////////wD/////' +
  'AAD///////////////////////////////////////8H4P///////////////////////////////////////wAA////////' +
  '/wAAMP//AP//////////////////////gP///////////////wAIAP//AP////////////////8FgP////8AAP//////////' +
  '//////8AAP///////////wAA////AAAA/////////////////////////wCAAPBz8EAAAB8AAAD/////////////////////' +
  '////AAAAAAAAAAAA//////////////////////////////8A/////wAA////////////////////////////////////////' +
  'D+D///////////////////////////////////////8AAP////////8AAAD//wH//////////////////////zj/////////' +
  '//////8AAAD//wD/////////////////D8D/////AyD/////////////////AAD///////////8AAP///wAAAP//////////' +
  '//////////////8IcAPAf/4GAfeAAAAA/////////////////////////wgAAAAAAAAAAP//////////////////////////' +
  '////AP////8AAP///////////////////////////////////////xfQ////////////////////////////////////////' +
  'AAD/////////AAAA//8E//////////////////////8A////////////////AAAB//+A/////////////////x/g/////wAA' +
  '/////////////////wAA////////////AAD///8AAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAA/////wAAAIBgAAAA' +
  'AUAAAIMAAAIAAAKAAoAAAkkAIQhiIxBAAP8AAAgggQAgIAADJgAA/wAA/wACAAAICAAACP9ECAAA/////wD/AP//////AP//' +
  '/wAA/wSg////AP//AAD/////AP8Aj4D//////////////////////////////4D/AP//AAABgP8AAAAAAP//////////////' +
  '/////////////wAAAYwA//8AAAAAAP8A////////////////////////AACgB/8AAAAAAEAAAAAA////////////////////' +
  'AAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAP////8AAACgAAAAAAEAAABCAAACAAACAAIAAAFSAAAKZqM4RwD/AEAIIKAA' +
  'IKAABkMAAP8AAP8AAgAAEAwAAAj/RBAgAP////8A/wD//////wD///8AAP8AAP///wD//wAA/////wD/AQPA////////////' +
  '//////////////////8A/xD//wAQAYD/ACgAAAD///////////////////////////8AAgIOAP//YAAIAAD/AP//////////' +
  '/////////////xABcA//ASEABgAQAAAAAP///////////////////wAAAAAAAAAAAIAAMiAKAAAAAAAAAAAAAAAAAAD/////' +
  'AAAAoAAoAAABAAAAaAAAAwAAAgACgAABpAAACgAAAAAA/wBACCCgAkKgAgwBAAD/AAr/AAIAgCAEAAAI/0QQIAj/////AP+A' +
  '//////8A////AgD/AAD///8A//8AAP////8A/wAB4P//////////////////////////////AP8A//8AIAeA/wgA0AAA////' +
  '////////////////////////AAAABwD//wIAAwAC/wD///////////////////////8QABAH/wIwIAEACACACAD/////////' +
  '//////////8AAABAAAAAAAGAAA0gGAABgAABAAEAADAASAAA/////wAAAKABBgggASAzESQADAIAgAIAAoAAAJAAAAoAAAAA' +
  'Av8gAAgQAABAABAZAJBA/wAA/ygAIABAAgAASv8EEAAA/////wD/AP//////AP///wgA/wAA////AP//AAD/////AP8CAeD/' +
  '/////////////////////////////wD/AP//ABwHAP8AAAAAAP///////////////////////////wEDiAeA//8ACAAQAP8A' +
  '////////////////////////AAAgD/8CkAIAIAIAIAIA////////////////////AAAAwAAAAAABAAAEkDIAAwAAAwADAAAQ' +
  'AYAABP/////zEDCABgISEEig9zgQC4wCm89CmYITBjDAQAACAAAAAAD/AEAEAQAgAAAAAAAAAP8AAP8AAAAAgAEAAAr/QBAA' +
  'AP////8A/wD//////wD///8QgP8AAP///wj//wAC/////wD/AAHg//////////////////////////////8A/wD//wBDxwD/' +
  'AAAAGAD///////////////////////////8CAGAHgP//AAAACAD/AP///////////////////////wAEYB//BJABAAgAgAAA' +
  'AP///////////////////yGAAIAAAAAAAQRCAkhAZgEMIQIAAgAACgMgAAz/////Ixny0CQQIBAgoAAAGAAAAoAAApACk0Yh' +
  'KG8YCgAREEYA/wAAAAIAAAAAAAAAAAD/IAD/AAAAAAAAAAAA/0IQAAD/////AP8A//////8w////AAD/AAD///8Q//8gAP//' +
  '//8A/wcP8P//////////////////////////////AP8A//8AgGYA/wBAAACA////////////////////////////BAAAB4D/' +
  '/0AAIAEA/wD///////////////////////8ACEAe/wUAAGACAAAAAID///////////////////8jnMSgAABhOwEMYwNAwEID' +
  'DHECDgIZzM0GRiAI/////wAAAEAoECEAICAAAIgAAACAAACAAgAAAiQDGApiIAQIAP8AAAAEIgAAAAAAAAAA/wAA/wAABAAA' +
  'IAAAAP8gCAAA/////wD/AP//////AP///wAA/wAA////AP//AAD/////EP8AADD//////////////////////////////wD/' +
  'AP//BAAeAP8AAFAAAP///////////////////////////wJAUAeA//8EAAgAAP8A////////////////////////H4DADv8B' +
  'oQAAAQAAAgAA////////////////////ABjGgGKfQxEBQAABoYAAAgAAAgACGIREjIZ3CP////8AAAAACCABCCCgAAGEAAAA' +
  'AAAAgAIAAAQSAAAIZkBIEAD/AEAAEAAAAAAAAAAgAP8AAP8ACAAAAAIgBAD/EAQAQv////8v/wD//////wD///8AAP8AEP//' +
  '/wD//wAA/////wD/AAAA//////////////////////////////8A/wD//wEAYAD/AAADAAD/////////////////////////' +
  '//8AHhAHgP//AEABAAD/gP///////////////////////wBCgA7/AEBABABACAEAAP////////////////////8AgAGAJgAE' +
  'gBACACAAAAAAAP///////////////wD//wAA/wiAfeD//wD/AAAI/wAA////////////AP//AP///wAB/AD///////8gAP8A' +
  '//9A/////////////////wD/QCADwP//////AP////////////////////8A/wAAAADAAIAwAAD/AAAA//////8g////AP8A' +
  '//////8AAIIAAAH/AHD//wAAEAAAAP8A//////8A/////wAAAACAAAAA/wAAwP8CAP8ACAD/AP//////////AP8AABBAAP8F' +
  'gID/AAAAAAQAAP8AACAAAAAAAP//AAAQAIAAEAAAgP//AQAhAB4AAAAAAIAQAAAABAD///////////////8A//8AAP8cYB3A' +
  '//8I/wAABP8AAP///////////wD//8D///8AAAAA////////AAD/QP//QP////////////////8A/0AABcD//////wD/////' +
  '////////////////gP8AAAEAgABA+AAA/wAIAP//////AP///wD/AP//////AICSACAC/wCw//8BQAAAAAD/AP//////Av//' +
  '//8AAAAAAAgAAP8ABMD/KgD/IAAA/wD//////////0T/ABIggAD/KAAA/wEAAAAAIMD/AAAAAAAAAAD//wAAAQEAAAAAAAD/' +
  '/wEQIwAcAAAAAgBACAEAEAAA////////////////AP//AID/CBQdwP//BP+AAAD/QAD///////////8A//8A////AAACAP//' +
  '/////wAA/wD//yD/////////////////AP8ABAHg//////8A/////////////////////wD/AAAAAQBgADgBAP8AAAD/////' +
  '/wD///8A/wD//////wAAVABAAv9AMP//CAAAAAAA/wD//////wD/////AEAAIABAAAb/AAFA/wAA/wAACv8A//////////8A' +
  '/wAYAQAA/wAAgP8ABABAEABg/wAAABAAAAAA//8AAAkgAAIAAAAA//8BAEMBHAAIAAEAIAQAgAAAAP///////////////wD/' +
  '/wAA/34HiYD//wD/gAAC/wAC////////////EP//AP///wAABwD///////8AAP8A//8A/////////////////wD/AAAB4P//' +
  '////AP////////////////////8A/wAAAAEAQAA4AAD/AQAA//////8A////AP8A//////8ABEgAgAT/ADD//wAAAAAAAv8A' +
  '//////8A/////wSAAAAGAAgE/wACwP8AKf8AAAD/AP//////////AP8QCEAAAP8ABAD/AgQAgAAAEP8AEAAeAAAAAP//AACB' +
  'AAAAAAAAAP//AABCAQ+AkAAAgAACAAAAAED///////////////9A//8BAP+fAHAA//8C/wAAAP8AAP///////////wD//wD/' +
  '//8AAAcA////////AAD/AP//AP////////////////8I/wAAAOD//////wD/////////////////////AP8IAAACAEAB+AAA' +
  '/wAAAP//////AP///4D/AP//////AAJIAQAY/wCg//8AAAAAAAT/AP//////AP////8AgAAAIAAgAP8CAYD/AAD/AAAA/wD/' +
  '/////////wD/CAAAAAD/AAAA/wACACAAAAj/AAAAAAAAP8D//wAEQUCAAAAAAAD//wAEQgAP4aAAAEAIAQAgAAAg////////' +
  '////////AP//AAD/PwAAAP//AP9ACAD/EAD///////////8A//8A////AAAHgP///////wAE/wD//wD/////////////////' +
  'gP8AAADw//////8A/////////////////////wD/BgAABADAIBgAAP8AAAD//////wD///8B/wD//////wCAAAAAEP+BYP//' +
  'AAAAAAEA/wD//////wD/////QAAAAAAAQBD/AgOA/wAA/wABEP8A//////////8C/wSAAAAA/wACYP8AB+AAAAAC/3wAAAAB' +
  'AMBw//8AgAAAAAAAAAAA//8AAEoAC/kAAAAgBACAAAIAEP///////////////wD//wEA/x+AAAD//wD/AAAA/wAA////////' +
  '////AP//AP///0AAB4D///////8AAP8A//8A/////////////////wD/AAAAcP//////Af////////////////////8A/wEB' +
  'AAQAgAAoABL/AAAA//////8A////AP8A//////8KAAAEAED/gOD//wAAAAAgkP8A//////8A/////wAEEAAAAYAA/wEBgP8A' +
  'AP8AAAD/gP//////////Af8CAAAAQP8AAAD/AAAwAAAAAP/gAAAAAAgAAP//AAAAAAAAAAAgAP//AAAEAAd9gAAAEAIAABAA' +
  'ABD///////////////8A//8AAP8PgAAA//8A/wAAAP8AAP///////////wD//wD///8AAAOA////////AAD/AP//AP//////' +
  '//////////8A/0ABALD//////wD/////////////////////AP8AIAAIAIAAGAAA/wAABP//////AP///wD/Af//////AAAA' +
  'AAAA/wBg//8AAAAEAAL/IP//////AP////8BAGAAAAMAgP8AhwD/ICD/CAAA/5D//////////wD/AAAAAAD/AAAA/wQAIAAA' +
  'AAD/AAAAAAAAAAD//xBAAAAAAAADQAD/AAAAAAAAAAAAAAAAAAAAAAAAAEdHR0dFRUdHR0dHR0cAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAR0dHRUVFR0dHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHAAAAAEdHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'R0cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHRwAAAAAAAABGRkYAAEcAAAAAAAAAAAAAAAAAAAAAAEcAAAAAAAAA' +
  'AAAAAABHRkcAAEcAAAAAAAAAAAAAAAAAR0cAAAAARkYAAAAAAAAAAAAAAAAAR0cAAAAAAAAAAABHRwAAAEdGRkREREdERERE' +
  'R0RER0REREdEREdER0REREREREcAAAAARERER0RERERER0RER0RER0RER0RHRERERERER0RERERHAEdHRERERERHR0dHR0cA' +
  'R0cAR0dHR0dER0dHAEREREcAAAAARABHAAAAAABHAAAAR0cAR0cAAABHAABHRwAAAABHAERERAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAARwBHAABEREREAEVFRUVFAAAAAAAAAAAAAAAAAAAAAAAAAAAAREREREQAAEVFRUVBAEUAAAAAAAAAAAAAAAAAAAAA' +
  'AABEREREAEVFRUVFRUVFRUUAAAAAAAAAAAAAAAAAAAAAREREREREREVFRUVFRUVFRUUAAAAAAAAAAAAAAABHAABERABERERE' +
  'AABFAEVFRQBBRQAAAAAAAAAAAEcAAEcAAABEREREAAAAAAAARUcAQQAARQAAAAAAAAAAAAAAAABEAEREREQAAAAAAEcAAAAA' +
  'AAAAAAAAAAAAAAAARwBERERERERERERHAEdHRwAAAAAARwAAAEcARwAAAAAAREREREREAEREAABEREdHREQARwAAAAAARwAA' +
  'AABEREREREdERABEREQAR0cAREREAEcAAAAAAAAAAEcAREREREcAR0REAEREREdHR0cAR0RHR0dHR0cAAERERERER0dHR0UA'

/** Raw 6912-byte screen dump. Pass to `parseSCR()`. */
export const MINEFIELD_LOADING_SCR: Uint8Array = Uint8Array.from(atob(BASE64), (c) => c.charCodeAt(0))
